### ISSUE TITLE
GB2260 各语言实现

### ISSUE THREAD

**Issue by lepture** [cn/discussion#1]
现在定义出了第一份 spec，需要实现各语言的库。

https://github.com/cn/GB2260/blob/v0.1/spec.md

@tonyseek Python?

@lepture JavaScript?

@damonchen Go?

@shen2 PHP?

**Comment by damonchen** [comment]
Go有些特殊，属性名称或函数名都需要大写。

**Comment by lepture** [comment]
没问题啊，根据语言特点修改
